import {useState} from 'react';
import {KeyRound,Copy,Check,LoaderCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {workspaceRequest} from '@/lib/auth';
export function AccessLink({seller,disabled=false}:{seller:any,disabled?:boolean}){
 const[open,setOpen]=useState(false),[url,setUrl]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false);
 async function generate(){setOpen(true);setBusy(true);setError('');setUrl('');setCopied(false);try{const r=await workspaceRequest({method:'POST',body:JSON.stringify({action:'accessLink',data:{seller_id:seller.id}})});const j=await r.json();if(!r.ok)throw new Error(j.error);setUrl(j.url)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <><button className="text-button" disabled={disabled||!seller.active||busy} onClick={generate}><KeyRound size={16}/> Crear enlace de acceso</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>Acceso de {seller.name}</DialogTitle><DialogDescription>Compartí este enlace directamente con el vendedor para que elija su contraseña. Vence en 7 días y reemplaza cualquier enlace anterior.</DialogDescription></DialogHeader>{busy&&<LoaderCircle className="spin"/>}{error&&<p role="alert" className="form-error">{error}</p>}{url&&<><label className="field"><span>Enlace personal para {seller.email}</span><textarea readOnly value={url} onFocus={e=>e.target.select()} rows={4}/></label><button className="button primary" onClick={async()=>{try{await navigator.clipboard.writeText(url);setCopied(true)}catch{setError('Seleccioná el enlace y copialo manualmente.')}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copiado':'Copiar enlace'}</button><div className="form-hint">Si ya tiene cuenta de Patas a Casa, puede ingresar con su contraseña habitual. Este enlace no cambia contraseñas existentes.</div></>}</DialogContent></Dialog></>;
}
