import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ShieldCheck,ArrowRight,LoaderCircle,Eye,EyeOff} from 'lucide-react';
import Dashboard from './dashboard';
import {auth,publicRequest} from '@/lib/auth';
import './globals.css';
function App(){
 const[session,setSession]=useState<any>(null),[loading,setLoading]=useState(true),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[invite,setInvite]=useState<any>(null);
 const[token,setToken]=useState(()=>new URLSearchParams(location.hash.slice(1)).get('alta')||'');
 useEffect(()=>{auth.getSession().then(({data}:any)=>{setSession(data.session);setLoading(false)}).catch(()=>{setError('No pudimos recuperar la sesión. Volvé a ingresar.');setLoading(false)});const{data:{subscription}}=auth.onAuthStateChange((_event:string,s:any)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(token){setBusy(true);publicRequest({action:'invitationInfo',token}).then(i=>{setInvite(i);setEmail(i.email)}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}},[token]);
 const clearInvite=()=>{setToken('');setInvite(null);history.replaceState({},'',location.pathname)};
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{
  if(token){if(!invite)throw new Error('Pedile a administración un nuevo enlace de acceso.');const r=await publicRequest({action:'activate',token,password});clearInvite();if(r.existing){setPassword('');setNotice('Ese correo ya tiene una cuenta de Patas a Casa. Ingresá con tu contraseña habitual o recuperala desde el enlace de abajo.');return;}}
  const{error}=await auth.signInWithPassword({email:email.trim(),password});if(error)throw new Error(error.code==='email_not_confirmed'?'Primero confirmá tu correo. Revisá tu bandeja de entrada.':'No pudimos ingresar. Revisá el correo y la contraseña.');setPassword('');
 }catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(loading)return <div className="auth-page"><LoaderCircle className="spin"/><p>Abriendo tu espacio de trabajo…</p></div>;
 if(session&&!token)return <Dashboard onSignOut={async()=>{await auth.signOut({scope:'local'});setSession(null)}}/>;
 return <main className="auth-page"><section className="auth-card"><img className="auth-logo" src="/ventas/logo.svg" alt="Patas a Casa"/><div className="auth-label"><ShieldCheck size={15}/> ACCESO PRIVADO</div><h1>{token?'Activá tu acceso':'Tu gestión comercial'}</h1><p>{invite?`Hola, ${invite.name}. Elegí una contraseña para empezar.`:'Ingresá para organizar tus comercios, visitas y ventas.'}</p><form onSubmit={submit}><label className="field"><span>Correo electrónico</span><input type="email" required autoComplete="username" value={email} readOnly={!!token} onChange={e=>setEmail(e.target.value)} placeholder="tu@email.com"/></label><label className="field"><span>{token?'Elegí tu contraseña':'Contraseña'}</span><div className="auth-password"><input type={show?'text':'password'} required minLength={token?10:undefined} maxLength={128} autoComplete={token?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" className="icon-button" aria-label={show?'Ocultar contraseña':'Mostrar contraseña'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{token&&<small>Al menos 10 caracteres. El enlace funciona una sola vez.</small>}{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status" className="note-box">{notice}</p>}<button type="submit" className="button primary full" disabled={busy||(!!token&&!invite)}>{busy?<LoaderCircle size={18} className="spin"/>:<ArrowRight size={18}/>} {busy?'Un momento…':token?'Crear mi acceso':'Ingresar'}</button></form>{token?<button className="text-button" onClick={clearInvite}>Ya tengo cuenta: ingresar</button>:<a className="text-button" href="/mi-cuenta/recuperar/" target="_blank" rel="noreferrer">Olvidé mi contraseña</a>}<div className="auth-foot">Solo pueden entrar las personas habilitadas por Patas a Casa.{!token&&<span> Si ya tenés una cuenta de Patas a Casa, usá ese mismo correo y contraseña.</span>}</div></section><p className="auth-credit">Patas a Casa · Gestión comercial</p></main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
