import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import {createRequire} from 'node:module';
// Load actual edge business rules while replacing only Deno package specifiers.
const require=createRequire(import.meta.url),cache={};
function load(file){if(cache[file])return cache[file].exports;const module={exports:{}};cache[file]=module;const source=fs.readFileSync(file,'utf8').replaceAll('npm:zod@3.25.76','zod');const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','module','exports',js)(id=>id.startsWith('.')?load(path.resolve(path.dirname(file),id)):require(id),module,module.exports);return module.exports;}
const {access,visible,change}=load(path.resolve('../../supabase/functions/patas-sales/workspace.ts'));
const {defaults,commissionSummary}=load(path.resolve('../../supabase/functions/patas-sales/domain.ts'));
const owner={id:'owner',email:'owner@example.test'},seller={id:'u1',email:'s1@example.test'},other={id:'u2',email:'s2@example.test'};
const state={owner_id:'owner',owner_email:owner.email,settings:{...defaults},sellers:[],shops:[],visits:[],orders:[],payments:[],commissions:[],kits:[]};
const act=(action,data,user=owner)=>change(state,user,action,data);
assert.throws(()=>access(state,seller));
act('seller',{id:'s1',name:'Vendedor Uno',email:seller.email,phone:'',zone:'Mendoza',map_url:'',active:1});
act('seller',{id:'s2',name:'Vendedor Dos',email:other.email,phone:'',zone:'Mendoza',map_url:'',active:1});
const shop={name:'Comercio de prueba',address:'Dirección de prueba',zone:'',contact:'',phone:'',status:'Pendiente',next_visit:'',map_url:'',notes:''};
act('shop',{...shop,id:'c1',seller_id:'s1'});act('shop',{...shop,id:'c2',seller_id:'s2'});
assert.equal(visible(state,seller).shops.length,1);
const quick=act('quickShop',{name:'Local espontáneo',address:'',zone:'Centro'},seller);assert.equal(state.shops.find(s=>s.id===quick.id)?.seller_id,'s1');assert.equal(visible(state,seller).shops.length,2);
act('shop',{...shop,id:'c3',seller_id:'s2'},seller);assert.equal(state.shops.find(s=>s.id==='c3')?.seller_id,'s1');
assert.throws(()=>act('seller',{...state.sellers[0],email:'hijack@example.test'},seller));
assert.throws(()=>act('visit',{id:'v1',shop_id:'c2',result:'Interesado',notes:'',next_visit:''},seller));
act('visit',{id:'v1',shop_id:'c1',result:'Interesado',notes:'Visita',next_visit:''},seller);
const item={model:'Circular grande · 31 mm',color:'Naranja',quantity:6,price:7000};
const order={id:'o1',shop_id:'c1',items:[item],delivery:'',notes:''};
assert.throws(()=>act('order',{...order,items:[{...item,price:1}]},seller));
act('order',order,seller);act('order',order,seller);assert.equal(state.orders.length,1);assert.equal(state.orders[0].total,42000);
assert.throws(()=>act('payment',{id:'p0',order_id:'o1',amount:42001,method:'Efectivo',reference:''}));
act('payment',{id:'p1',order_id:'o1',amount:21000,method:'Efectivo',reference:''});assert.equal(commissionSummary(state.orders,state.payments,state.commissions,'s1').earned,0);
act('payment',{id:'p2',order_id:'o1',amount:21000,method:'Efectivo',reference:''});act('payment',{id:'p2',order_id:'o1',amount:21000,method:'Efectivo',reference:''});
assert.equal(state.payments.length,2);assert.equal(commissionSummary(state.orders,state.payments,state.commissions,'s1').earned,7000);
assert.throws(()=>act('orderStatus',{id:'o1',status:'Cancelado'}));
act('order',{...order,id:'o2',items:[{...item,quantity:2}]},seller);act('payment',{id:'p3',order_id:'o2',amount:14000,method:'Transferencia',reference:''});
assert.equal(commissionSummary(state.orders,state.payments,state.commissions,'s1').earned,14000);
assert.throws(()=>act('commission',{id:'m1',seller_id:'s1',amount:14001,reference:''}));
act('commission',{id:'m1',seller_id:'s1',amount:14000,reference:''});act('commission',{id:'m1',seller_id:'s1',amount:14000,reference:''});assert.equal(state.commissions.length,1);
assert.equal(visible(state,other).orders.length,0);assert.equal(visible(state,other).payments.length,0);
act('order',{...order,id:'o3'},seller);act('orderStatus',{id:'o3',status:'Cancelado'});assert.throws(()=>act('payment',{id:'p4',order_id:'o3',amount:1,method:'Efectivo',reference:''}));
act('seller',{...state.sellers[0],active:0});assert.throws(()=>visible(state,seller));
assert.throws(()=>visible(state,{id:'random',email:'random@example.test',user_metadata:{admin:true}}));
const snapshot=structuredClone(state);assert.throws(()=>change(snapshot,other,'settings',{...defaults,adminEmails:other.email}));
console.log('PASS: seller isolation, disabled access, no metadata escalation, schema validation, orders, partial payments, duplicate retries, cancellation, commission accumulation and overpayment protection.');
