create table if not exists public.admin_tag_events (
  id bigint generated by default as identity primary key,
  public_code text not null,
  action text not null check (action in ('reset','block','unblock')),
  previous_pet_id uuid,
  previous_owner_id uuid,
  previous_owner_email text,
  previous_pet_name text,
  previous_activated_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.admin_tag_events enable row level security;
revoke all on table public.admin_tag_events from anon, authenticated;

create index if not exists admin_tag_events_public_code_created_idx
  on public.admin_tag_events (public_code, created_at desc);

create or replace function public.admin_tag_dashboard(
  p_admin_key text,
  p_search text default '',
  p_status text default 'all',
  p_limit integer default 100,
  p_offset integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'extensions', 'auth', 'pg_temp'
as $function$
declare
  v_hash text;
  v_limit integer := greatest(1, least(coalesce(p_limit, 100), 200));
  v_offset integer := greatest(0, coalesce(p_offset, 0));
  v_search text := trim(coalesce(p_search, ''));
  v_status text := lower(trim(coalesce(p_status, 'all')));
  v_stats jsonb;
  v_items jsonb;
  v_filtered_count bigint;
begin
  select key_hash into v_hash from public.app_admin_config where id = 1;
  if v_hash is null or extensions.crypt(coalesce(p_admin_key, ''), v_hash) <> v_hash then
    raise exception 'Clave de administrador incorrecta' using errcode = '42501';
  end if;

  if v_status not in ('all', 'active', 'available', 'pending', 'blocked') then
    v_status := 'all';
  end if;

  with base as (
    select
      t.id as tag_id,
      t.public_code,
      t.created_at,
      t.activated_at,
      t.blocked_at,
      t.pet_id,
      p.name as pet_name,
      p.species,
      p.owner_id,
      u.email as owner_email,
      exists (
        select 1
        from public.pending_owner_claims poc
        where poc.tag_id = t.id
          and poc.consumed_at is null
          and poc.expires_at > now()
      ) as pending_claim
    from public.tags t
    left join public.pets p on p.id = t.pet_id
    left join auth.users u on u.id = p.owner_id
  ), states as (
    select *,
      case
        when blocked_at is not null then 'blocked'
        when activated_at is not null and pet_id is not null then 'active'
        when pending_claim then 'pending'
        else 'available'
      end as state
    from base
  )
  select jsonb_build_object(
    'total', count(*),
    'active', count(*) filter (where state = 'active'),
    'available', count(*) filter (where state = 'available'),
    'pending', count(*) filter (where state = 'pending'),
    'blocked', count(*) filter (where state = 'blocked')
  ) into v_stats
  from states;

  with base as (
    select
      t.id as tag_id,
      t.public_code,
      t.created_at,
      t.activated_at,
      t.blocked_at,
      t.pet_id,
      p.name as pet_name,
      p.species,
      p.owner_id,
      u.email as owner_email,
      exists (
        select 1
        from public.pending_owner_claims poc
        where poc.tag_id = t.id
          and poc.consumed_at is null
          and poc.expires_at > now()
      ) as pending_claim,
      (
        select sl.short_url
        from public.short_links sl
        where sl.public_code = t.public_code
        order by sl.created_at desc
        limit 1
      ) as short_url,
      (
        select e.action
        from public.admin_tag_events e
        where e.public_code = t.public_code
        order by e.created_at desc
        limit 1
      ) as last_admin_action,
      (
        select e.created_at
        from public.admin_tag_events e
        where e.public_code = t.public_code
        order by e.created_at desc
        limit 1
      ) as last_admin_action_at
    from public.tags t
    left join public.pets p on p.id = t.pet_id
    left join auth.users u on u.id = p.owner_id
  ), states as (
    select *,
      case
        when blocked_at is not null then 'blocked'
        when activated_at is not null and pet_id is not null then 'active'
        when pending_claim then 'pending'
        else 'available'
      end as state
    from base
  ), filtered as (
    select *
    from states
    where (v_status = 'all' or state = v_status)
      and (
        v_search = ''
        or public_code ilike '%' || v_search || '%'
        or coalesce(pet_name, '') ilike '%' || v_search || '%'
        or coalesce(owner_email, '') ilike '%' || v_search || '%'
        or coalesce(short_url, '') ilike '%' || v_search || '%'
      )
  )
  select count(*) into v_filtered_count from filtered;

  with base as (
    select
      t.public_code,
      t.created_at,
      t.activated_at,
      t.blocked_at,
      t.pet_id,
      p.name as pet_name,
      p.species,
      p.owner_id,
      u.email as owner_email,
      exists (
        select 1
        from public.pending_owner_claims poc
        where poc.tag_id = t.id
          and poc.consumed_at is null
          and poc.expires_at > now()
      ) as pending_claim,
      (
        select sl.short_url
        from public.short_links sl
        where sl.public_code = t.public_code
        order by sl.created_at desc
        limit 1
      ) as short_url,
      (
        select e.action
        from public.admin_tag_events e
        where e.public_code = t.public_code
        order by e.created_at desc
        limit 1
      ) as last_admin_action,
      (
        select e.created_at
        from public.admin_tag_events e
        where e.public_code = t.public_code
        order by e.created_at desc
        limit 1
      ) as last_admin_action_at
    from public.tags t
    left join public.pets p on p.id = t.pet_id
    left join auth.users u on u.id = p.owner_id
  ), states as (
    select *,
      case
        when blocked_at is not null then 'blocked'
        when activated_at is not null and pet_id is not null then 'active'
        when pending_claim then 'pending'
        else 'available'
      end as state
    from base
  ), filtered as (
    select *
    from states
    where (v_status = 'all' or state = v_status)
      and (
        v_search = ''
        or public_code ilike '%' || v_search || '%'
        or coalesce(pet_name, '') ilike '%' || v_search || '%'
        or coalesce(owner_email, '') ilike '%' || v_search || '%'
        or coalesce(short_url, '') ilike '%' || v_search || '%'
      )
    order by created_at desc
    limit v_limit offset v_offset
  )
  select coalesce(jsonb_agg(to_jsonb(filtered) order by created_at desc), '[]'::jsonb)
    into v_items
  from filtered;

  return jsonb_build_object(
    'stats', coalesce(v_stats, '{}'::jsonb),
    'items', coalesce(v_items, '[]'::jsonb),
    'filtered_count', coalesce(v_filtered_count, 0),
    'limit', v_limit,
    'offset', v_offset
  );
end;
$function$;

create or replace function public.admin_tag_action(
  p_admin_key text,
  p_public_code text,
  p_action text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'extensions', 'auth', 'pg_temp'
as $function$
declare
  v_hash text;
  v_code text := upper(regexp_replace(trim(coalesce(p_public_code, '')), '[^A-Z0-9]', '', 'g'));
  v_action text := lower(trim(coalesce(p_action, '')));
  v_tag public.tags%rowtype;
  v_pet_name text;
  v_owner_id uuid;
  v_owner_email text;
begin
  select key_hash into v_hash from public.app_admin_config where id = 1;
  if v_hash is null or extensions.crypt(coalesce(p_admin_key, ''), v_hash) <> v_hash then
    raise exception 'Clave de administrador incorrecta' using errcode = '42501';
  end if;

  if v_action not in ('reset', 'block', 'unblock') then
    raise exception 'Acción inválida' using errcode = '22023';
  end if;

  select * into v_tag
  from public.tags
  where public_code = v_code
  for update;

  if not found then
    raise exception 'Chapita no encontrada' using errcode = 'P0002';
  end if;

  if v_tag.pet_id is not null then
    select p.name, p.owner_id, u.email
      into v_pet_name, v_owner_id, v_owner_email
    from public.pets p
    left join auth.users u on u.id = p.owner_id
    where p.id = v_tag.pet_id;
  end if;

  if v_action = 'reset' then
    delete from public.pending_owner_claims where tag_id = v_tag.id;

    update public.tags
      set pet_id = null,
          activated_at = null,
          blocked_at = null
    where id = v_tag.id;

    if v_tag.pet_id is not null then
      delete from public.pets where id = v_tag.pet_id;
    end if;

    delete from public.pets where public_code = v_code;

  elsif v_action = 'block' then
    update public.tags
      set blocked_at = coalesce(blocked_at, now())
    where id = v_tag.id;

  elsif v_action = 'unblock' then
    update public.tags
      set blocked_at = null
    where id = v_tag.id;
  end if;

  insert into public.admin_tag_events(
    public_code,
    action,
    previous_pet_id,
    previous_owner_id,
    previous_owner_email,
    previous_pet_name,
    previous_activated_at
  ) values (
    v_code,
    v_action,
    v_tag.pet_id,
    v_owner_id,
    v_owner_email,
    v_pet_name,
    v_tag.activated_at
  );

  return jsonb_build_object(
    'ok', true,
    'public_code', v_code,
    'action', v_action,
    'pin_preserved', true,
    'qr_preserved', true,
    'previous_pet_name', v_pet_name,
    'previous_owner_email', v_owner_email
  );
end;
$function$;

revoke all on function public.admin_tag_dashboard(text, text, text, integer, integer) from public, anon, authenticated;
revoke all on function public.admin_tag_action(text, text, text) from public, anon, authenticated;
grant execute on function public.admin_tag_dashboard(text, text, text, integer, integer) to service_role;
grant execute on function public.admin_tag_action(text, text, text) to service_role;
