-- Keep every existing tag on the PIN flow. QR-only activation is enabled
-- individually after a physical tag has been selected for testing or sale.
alter table public.tags
  add column if not exists activation_mode text not null default 'pin';

do $migration$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'tags_activation_mode_check'
      and conrelid = 'public.tags'::regclass
  ) then
    alter table public.tags
      add constraint tags_activation_mode_check
      check (activation_mode in ('pin', 'qr'));
  end if;
end
$migration$;

comment on column public.tags.activation_mode is
  'pin keeps the legacy private-PIN flow; qr allows a verified account to claim the physical tag from its QR.';

create table if not exists public.qr_activation_attempts (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  public_code text not null,
  created_at timestamptz not null default now()
);

alter table public.qr_activation_attempts enable row level security;
revoke all on table public.qr_activation_attempts from anon, authenticated;
revoke all on sequence public.qr_activation_attempts_id_seq from anon, authenticated;

create index if not exists qr_activation_attempts_user_created_idx
  on public.qr_activation_attempts (auth_user_id, created_at desc);

create index if not exists qr_activation_attempts_created_idx
  on public.qr_activation_attempts (created_at);

comment on table public.qr_activation_attempts is
  'Server-only attempt log used to limit QR-only activation guesses per verified account.';

-- First controlled rollout: only these two physical tags use QR-only activation.
update public.tags
set activation_mode = 'qr'
where public_code in ('A09215F0', '36C76BB2');
